name: Build and Test Docker Image

on:
  workflow_call:
  pull_request:
    branches: [ "master", "github-actions" ]

jobs:

  build_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build Docker Image
      run: make mosquitto-unraid
      
    - name: Build Test Image
      run: make mosquitto-unraid-tests
      
    - name: Test Docker Image
      run: make test
