name: Build and Test Docker Image

on:
  workflow_call:
    inputs:
      archive:
        required: false
        type: boolean
        default: false
  pull_request:
    branches: [ "master" ]

jobs:

  build_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build Docker Image
      run: make mosquitto-unraid
      
    - name: Build Test Image
      run: make mosquitto-unraid-tests
      
    - name: Test Docker Image
      run: make test

    - name: Export Docker Image
      if: ${{ inputs.archive && github.ref == 'refs/heads/master' }}
      run: docker save --output docker-image.tar mosquitto-unraid

    - name: Upload Docker Image
      uses: actions/upload-artifact@v3
      if: ${{ inputs.archive && github.ref == 'refs/heads/master' }}
      with:
        name: docker-image
        path: docker-image.tar
