name: Deploy Docker Image

on:
  push:
    branches: [ "master" ]

jobs:

  build_test:
    uses: ./.github/workflows/build_test.yml
    with:
      archive: true
    secrets: inherit

  deploy:
    needs: build_test
    runs-on: ubuntu-latest
    steps:
    - name: Download Docker Image
      uses: actions/download-artifact@v4
      with:
        name: docker-image

    - name: Load Docker Image
      run: docker load --input docker-image.tar

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push to Docker Hub as :beta
      run: |
        docker tag mosquitto-unraid cmccambridge/mosquitto-unraid:beta
        docker push cmccambridge/mosquitto-unraid:beta
